
        
        
        name: Sync Google Drive JSON

# Установлено на 14:12 по Николаеву (11:12 UTC). workflow_dispatch подтверждает ручной запуск.
on:
  schedule:
    - cron: '12 11 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download JSON from Google Drive and Validate
      run: |
        DRIVE_ID="1aYWqdRjy6q9rIM_QlwgoTfGr8yUpIcPH"
        DOWNLOAD_URL="https://drive.google.com/uc?export=download&id=1aYWqdRjy6q9rIM_QlwgoTfGr8yUpIcPH"
        OUTPUT_PATH="data/data.json"
        
        echo "Attempting to download file from Google Drive..."
        
        # 1. Используем агрессивный curl с обработкой cookies для стабильности
        curl -L -c /tmp/cookies.txt "$DOWNLOAD_URL" -o "$OUTPUT_PATH"
        
        # 2. Диагностика: Проверяем размер скачанного файла
        FILE_SIZE=$(wc -c < "$OUTPUT_PATH")
        echo "::notice::Downloaded file size: $FILE_SIZE bytes."
        
        # 3. Проверка на ошибку Google: Предотвращает коммит HTML
        if [ $FILE_SIZE -lt 500 ]; then
          echo "::error::Downloaded file is suspiciously small ($FILE_SIZE bytes). Google Drive likely returned an error page."
          exit 1 # Завершаем Action с ошибкой
        fi

    - name: Commit and Push if file changed
      # ИСПРАВЛЕНИЕ: Используем версию v4, которая корректно работает с параметром 'files'
      uses: stefanzweifel/git-auto-commit-action@v4 
      with:
        files: data/data.json # <-- ИСПРАВЛЕНО: используем 'files'
        commit_message: "Automated: Update data.json from Google Drive"
        commit_user_name: GitHub Actions Bot
        commit_user_email: actions@github.com
