name: Sync Google Drive JSON

# 1. Запуск ежедневно в 14:00 по UTC
on:
  schedule:
    # Запускать каждый день в 14 часов 0 минут по UTC.
    - cron: '12 11 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      # Загружает код, включая папку /data
      uses: actions/checkout@v4

    - name: Download JSON from Google Drive
      # Скачивание и сохранение файла ПРЯМО В ПАПКУ data/
      run: |
        DRIVE_ID="1aYWqdRjy6q9rIM_QlwgoTfGr8yUpIcPH" # <--- ОБЯЗАТЕЛЬНО ЗАМЕНИТЬ!
        DOWNLOAD_URL="https://drive.google.com/uc?export=download&id=1aYWqdRjy6q9rIM_QlwgoTfGr8yUpIcPH"
        # Скачиваем файл и сохраняем его как data/data.json
        curl -L "$DOWNLOAD_URL" -o data/data.json
        
    - name: Commit and Push if file changed
      # Указываем, что нужно отслеживать файл по новому пути
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        files: data/data.json # <-- ОБНОВЛЕННЫЙ ПУТЬ
        commit_message: "Automated: Update data.json from Google Drive"
        commit_user_name: GitHub Actions Bot
        commit_user_email: actions@github.com
